# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandmanagement', '0003_auto_20170302_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_name',
            field=models.CharField(default='oldnoname', max_length=300),
            preserve_default=False,
        ),
    ]
