# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandmanagement', '0004_member_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('finished', models.BooleanField()),
                ('difficulty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('due_date', models.DateTimeField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bandmanagement.Member')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandmanagement.Band')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
